stages:
  - secrets-scanning
  - code-linting
  - code-analysis
  - docker-linting
  - build

variables:
  ALUMNO: devops-grupo11
  TAG: devops-runner
# 1.3 Build de codigo

dockerize-all:
  image: docker:24.0.2  # Usa la imagen base de Docker
  stage: build
  tags: [$TAG]
  variables:
    DOCKER_IMAGE_LATEST: $CI_REGISTRY/$ALUMNO:latest  # Imagen común para el tag latest
    CA_CERTIFICATE: "$CA_CERTIFICATE"  # Certificado CA personalizado si es necesario
    DOCKER_BUILDKIT: "1"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:24.0.2-dind
      alias: docker
      command:
        - /bin/sh
        - -c
        - |
          echo "$CA_CERTIFICATE" > /usr/local/share/ca-certificates/my-ca.crt && update-ca-certificates && dockerd-entrypoint.sh || exit
  before_script:
    # Verificar Docker y Login
    - echo "Verificando la versión de Docker..."
    - docker version
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Instalando curl y docker-compose..."
    - apk update && apk add --no-cache curl  # Instala curl si es necesario
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - /usr/local/bin/docker-compose --version  # Verifica la instalación de docker-compose
  script:
    # Construir y subir imágenes usando docker-compose
    - echo "Construyendo imágenes Docker para todos los servicios con docker-compose..."
    - docker-compose -f docker-compose.yaml build --no-cache  # Construcción de las imágenes sin caché
    - docker-compose -f docker-compose.yaml push  # Subir todas las imágenes construidas al registro de Docker
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - docker-compose.yaml  # Asegura que docker-compose.yaml esté presente
