stages:
  - secrets-scanning
  - code-linting
  - code-analysis
  - docker-linting
  - build

variables:
  ALUMNO: devops-grupo11
  TAG: devops-runner

docker-lint-python:
  image: python:3.9-bullseye
  stage: docker-linting
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: python-docker-linting-$ALUMNO.txt
    SCAN_DIRECTORY: python-api
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install checkov
    - pip install semgrep==0.38.0 jsonschema==3.2.0 ruamel.yaml==0.16.10
    - checkov -f $SCAN_DIRECTORY/Dockerfile --framework dockerfile
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME

docker-lint-node:
  image: python:3.9-bullseye
  stage: docker-linting
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: node-docker-linting-$ALUMNO.txt
    SCAN_DIRECTORY: node-api
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install checkov
    - pip install semgrep==0.38.0 jsonschema==3.2.0 ruamel.yaml==0.16.10
    - checkov -f $SCAN_DIRECTORY/Dockerfile --framework dockerfile
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME

docker-lint-db:
  image: python:3.9-bullseye
  stage: docker-linting
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: db-docker-linting-$ALUMNO.txt
    SCAN_DIRECTORY: db
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install checkov
    - pip install semgrep==0.38.0 jsonschema==3.2.0 ruamel.yaml==0.16.10
    - checkov -f $SCAN_DIRECTORY/Dockerfile --framework dockerfile
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME

docker-lint-nginx:
  image: python:3.9-bullseye
  stage: docker-linting
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: nginx-docker-linting-$ALUMNO.txt
    SCAN_DIRECTORY: nginx
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install checkov
    - pip install semgrep==0.38.0 jsonschema==3.2.0 ruamel.yaml==0.16.10
    - checkov -f $SCAN_DIRECTORY/Dockerfile --framework dockerfile
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME

docker-lint-web:
  image: python:3.9-bullseye
  stage: docker-linting
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: web-docker-linting-$ALUMNO.txt
    SCAN_DIRECTORY: web
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install checkov
    - pip install semgrep==0.38.0 jsonschema==3.2.0 ruamel.yaml==0.16.10
    - checkov -f $SCAN_DIRECTORY/Dockerfile --framework dockerfile
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME