stages:
  - code-analysis

variables:
  ALUMNO: devops-grupo11
  TAG: devops-runner

sast-scan-python:
  image: python:3.9-bullseye
  stage: code-analysis
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: sast-scan-python-$ALUMNO.txt
    SCAN_DIRECTORY: python-api
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install bandit
    - bandit -r $SCAN_DIRECTORY > $ARTIFACT_FILE_NAME
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME

sca-scan-python:
  image: python:3.9-bullseye
  stage: code-analysis
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: sca-scan-python-$ALUMNO.txt
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install safety
    - safety check --output-file $ARTIFACT_FILE_NAME
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME

