stages:
  - secrets-scanning

variables:
  ALUMNO: devops-grupo11
  TAG: devops-runner

# Job para escanear secretos en la API de Python
scan-secrets-python:
  image: ubuntu
  stage: secrets-scanning
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: scan-secrets-python-$ALUMNO.txt
  script:
    - apt update
    - apt install python3 python3-pip python3-virtualenv python3-venv -y
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install detect-secrets
    - cd python-api  # Cambia al directorio de la API de Python
    - detect-secrets scan . --all-files --exclude-files venv/ > "../$ARTIFACT_FILE_NAME"
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME


# Job para escanear secretos en la API de Node
scan-secrets-node:
  image: python:3.9-bullseye
  stage: secrets-scanning
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: scan-secrets-node-$ALUMNO.txt
  script:
    - apt update
    - apt install -y nodejs npm  # Instala Node en la imagen de Python
    - pip install detect-secrets
    - cd node-api
    - npm install  # Instala las dependencias de Node definidas en package.json
    - detect-secrets scan . --all-files > "../$ARTIFACT_FILE_NAME"
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME

# Job para escanear secretos en el frontend de React 
scan-secrets-react:
  image: node:18
  stage: secrets-scanning
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: scan-secrets-react-$ALUMNO.txt
  script:
    - apt update
    - apt install -y python3 python3-pip  # Instala Python y pip en la imagen de Node
    - pip3 install detect-secrets  # Instala detect-secrets
    - cd web  # Cambia al directorio del frontend React
    - npm install  # Instala las dependencias del proyecto React
    - detect-secrets scan . --all-files > "../$ARTIFACT_FILE_NAME"
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME