version: '3.8'

services:

  nginx-users:
    build: nginx/
    ports:
      - "8080:80"
    networks:
      - crud-users-net
    restart: always
    links:
      - api-users:api-users
    depends_on:
      - api-users


  api-users:
    build: api/
    networks:
      - crud-users-net
    depends_on: 
      - db-crud-users
    links:
      - "db-crud-users:db-crud-users"
    environment:
      MYSQL_DATABASE_USER: testuser
      MYSQL_DATABASE_PASSWORD: testpass
      MYSQL_DATABASE_DB: utn
      MYSQL_DATABASE_HOST: db-crud-users  # Nombre del servicio db en Docker Compose
      MYSQL_DATABASE_PORT: 3306
    ports:
      - "5000:5000"  # sacar después

  db-crud-users:
    build: db/
    restart: always
    networks:
      - crud-users-net
    volumes:
      - db-crud-users-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: utn
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"

volumes:
  db-crud-users-data:

networks:
  crud-users-net:
