version: '3.8'

services:

  nginx-users:
    build: nginx/
    ports:
      - "8080:80"
    networks:
      - crud-users-net
    restart: always
    depends_on:
      - api-users
      - api-node
      - web
    image: $CI_REGISTRY/nginx-$ALUMNO:latest

  api-node:
    build: node-api/
    restart: always
    networks:
      - crud-users-net
    image: $CI_REGISTRY/node-api-$ALUMNO:latest

  db-crud-users:
    build: db/
    restart: always
    networks:
      - crud-users-net
    volumes:
      - db-crud-users-data:/var/lib/mysql
    image: $CI_REGISTRY/db-$ALUMNO:latest
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: utn
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass

  api-users:
    build: python-api/
    restart: always
    networks:
      - crud-users-net
    depends_on: 
      - db-crud-users
    image: $CI_REGISTRY/python-api-$ALUMNO:latest
    environment:
      MYSQL_DATABASE_USER: testuser
      MYSQL_DATABASE_PASSWORD: testpass
      MYSQL_DATABASE_DB: utn
      MYSQL_DATABASE_HOST: db-crud-users
      MYSQL_DATABASE_PORT: 3306

  web:
    build: web/
    restart: always
    networks:
      - crud-users-net
    image: $CI_REGISTRY/web-$ALUMNO:latest

volumes:
  db-crud-users-data:

networks:
  crud-users-net:
