version: '3.8'

services:

  nginx-users:
    build: nginx/
    ports:
      - "8080:80"
    networks:
      - crud-users-net
    restart: always
    depends_on:
      - api-users

  api-node:
    build: node-api/
    restart: always
    ports:
      - "1000:1000"
    networks:
      - crud-users-net

  db-crud-users:
    build: db/
    restart: always
    networks:
      - crud-users-net
    volumes:
      - db-crud-users-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: utn
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    #ports:
    #  - "3306:3306"


  api-users:
    build: python-api/
    restart: always
    networks:
      - crud-users-net
    depends_on: 
      - db-crud-users
    environment:
      MYSQL_DATABASE_USER: testuser
      MYSQL_DATABASE_PASSWORD: testpass
      MYSQL_DATABASE_DB: utn
      MYSQL_DATABASE_HOST: db-crud-users
      MYSQL_DATABASE_PORT: 3306

volumes:
  db-crud-users-data:

networks:
  crud-users-net:
