version: '3.8'

services:

  nginx-users:
    build: nginx/
    restart: always
    ports:
      - "8080:80"
    networks:
      - crud-users-net
    depends_on:
      - api-users

  api-users:
    build: api/
    restart: always
    networks:
      - crud-users-net
    depends_on:
      - db-crud-users
    links: 
      - db-crud-users

  db-crud-users:
    build: db/
    restart: always
    volumes:
      - db-crud-users-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: utn
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    networks:
      - crud-users-net

volumes:
  db-crud-users-data:

networks:
  crud-users-net:

